In [2]:
import pandas as pd
import numpy as np

In [3]:
# Imports Mahalanobis Distance code
%run Pipeline_Code.ipynb

In [4]:
#file path to credit card csv file
file_path = os.path.join(os.path.expanduser("~"), "Desktop", "archive(2)", "creditcard.csv")
df = pd.read_csv(file_path) #read csv file as pandas object
CC_data = df.to_numpy() #CC_data will contain the Credit Card Fraud detection dataset as a numpy object

#Getting a features-only dataset
features = CC_data[0:50000]

fraud_instances = []
for i in range(len(features)):
    if features[i][-1] == 1:
        fraud_instances.append(i)

features = np.array([arr[:-1] for arr in features])  

labels = np.array(df["Class"][0:50000]) # labels

#Getting a features-only dataset
features2 = CC_data[50000:100000]

fraud_instances2 = []
for i in range(len(features)):
    if features2[i][-1] == 1:
        fraud_instances2.append(i)

features2 = np.array([arr[:-1] for arr in features2])  

labels2 = np.array(df["Class"][50000:100000]) # labels

In [6]:
distances = mahalanobisDistance(features, features)
threshold = findThresholdMD(distances, labels)
predictedTrainLabels = predictMD(threshold, features)
print(confusionMatrixMD(labels, predictedTrainLabels))
distances2 = mahalanobisDistance(features2, features2)
predictedTestLabels = predictMD(threshold, features2)
print(confusionMatrixMD(labels2, predictedTestLabels))

[[49736   116]
 [   89    59]]
[[49802   123]
 [   49    26]]


In [8]:
print(matrixScoresMD(confusionMatrixMD(labels2, predictedTestLabels), "precision"))
print(matrixScoresMD(confusionMatrixMD(labels2, predictedTestLabels), "recall"))
print(matrixScoresMD(confusionMatrixMD(labels2, predictedTestLabels), "f1score"))

0.174496644295302
0.3466666666666667
0.23214285714285715


In [5]:
from numpy import random

datapointIndices = random.randint(200000, size=(50000))

data = df.take(datapointIndices)

data = np.array(data)

randomFirstSetLabels = np.array(df["Class"][datapointIndices])

fraud_instances3 = []
for i in range(len(data)):
    if data[i][-1] == 1:
        fraud_instances3.append(i)


randomFirstSet = np.array([arr[:-1] for arr in data])  



datapointIndices2 = random.randint(200000, size=(50000))

data2 = df.take(datapointIndices2)

data2 = np.array(data2)

randomSecondSetLabels = np.array(df["Class"][datapointIndices2])

fraud_instances4 = []
for i in range(len(data)):
    if data2[i][-1] == 1:
        fraud_instances4.append(i)


randomSecondSet = np.array([arr[:-1] for arr in data2])  

In [6]:
distances3 = mahalanobisDistance(randomFirstSet, randomFirstSet)
threshold3 = findThresholdMD(distances3, randomFirstSetLabels)
predictedTrainLabels = predictMD(threshold3, randomFirstSet)
print(confusionMatrixMD(randomFirstSetLabels, predictedTrainLabels))

predictedTestLabels = predictMD(threshold3, randomSecondSet)
print(confusionMatrixMD(randomSecondSetLabels, predictedTestLabels))

[[49881     8]
 [  101    10]]
[[49907    15]
 [   77     1]]


In [6]:
print(matrixScoresMD(confusionMatrixMD(randomFirstSetLabels, predictedTrainLabels), "precision"))
print(matrixScoresMD(confusionMatrixMD(randomFirstSetLabels, predictedTrainLabels), "recall"))
print(matrixScoresMD(confusionMatrixMD(randomFirstSetLabels, predictedTrainLabels), "f1score"))

0.3424657534246575
0.2808988764044944
0.30864197530864196
